import pyautogui as pyag
import time as t
pyag.press("super")
pyag.write("Opera GX")
pyag.press("enter")
t.sleep(2.5)
pyag.write("instagram.com")
t.sleep(0.3)
pyag.press("enter")
t.sleep(3.5)
pyag.click(889, 305)
pyag.write("no")
pyag.hotkey('altright', '2')
pyag.write("thankyou.com")
t.sleep(1.0)
pyag.click(889, 355)
pyag.write("fakeahhaccountxd")
t.sleep(1.0)
pyag.click(889, 400)
