tupla = []
fruta = input("Diga uma fruta: ")
tupla.append(fruta)
fruta = input("Diga outra fruta: ")
tupla.append(fruta)
fruta = input("Diga mais uma fruta: ")
tupla.append(fruta)
fruta = input("Diga mais uma fruta: ")
tupla.append(fruta)
fruta = input("Diga mais uma fruta: ")
tupla.append(fruta)
fruta = input("Diga só mais uma fruta: ")
tupla.append(fruta)
tupla = tuple(tupla)
print(f"\nA sua tupla: {tupla}")
tupla_frutas = ("maça", "banana", "laranja", "uva", "abacaxi")
print(f"Outra tupla com frutas: {tupla_frutas}")
print(f"A primeira fruta da sua tupla é {tupla[0]}")
print(f"A última fruta da sua tupla é {tupla[-1]}")
if "kiwi" in tupla:
    print("A fruta 'kiwi' está na tupla!")
else:
    print("A fruta 'kiwi' não está na tupla!")
print(f"As primeiras 3 frutas da tupla são {tupla[0:3]}")
