tupla = []
numeros = int(input("Diga um número: "))
tupla.append(numeros)
numeros = int(input("Diga outro número: "))
tupla.append(numeros)
numeros = int(input("Diga mais um número: "))
tupla.append(numeros)
numeros = int(input("Diga mais um número: "))
tupla.append(numeros)
numeros = int(input("Diga mais um número: "))
tupla.append(numeros)
numeros = int(input("Diga só mais um número: "))
tupla.append(numeros)
tupla = tuple(tupla)
print(f"\nA sua tupla: {tupla}")
tupla_num = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print(f"Tupla com números de 1 a 10: {tupla_num}")
print(f"O maior número da sua tupla é {max(tupla)}")
print(f"O menor número da sua tupla é {min(tupla)}")
print(f"A soma de todos os números na sua tupla é {sum(tupla)}")
if 5 in tupla:
    print("O número 5 está na tupla!")
else:
    print("O número 5 não está na tupla!")
